route:
  receiver: switch_on
  repeat_interval: 30m
  routes:
    - receiver: switch_on
      match:
        alertname: HighTemperature
    - receiver: switch_off
      match:
        alertname: LowTemperature

receivers:
  - name: switch_on
    webhook_configs:
      - url: http://127.0.0.1:7000/on
  - name: switch_off
    webhook_configs:
      - url: http://127.0.0.1:7000/off
