rule_files:
  - /etc/prometheus/rules/*.yml

scrape_configs:
  - job_name: "onewire_exporter"
    scrape_interval: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ["127.0.0.1:8105"]
  - job_name: "cooler_power"
    scrape_interval: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ["127.0.0.1:7000"]

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["127.0.0.1:9093"]
