apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    uid: prometheus
    url: http://192.168.1.170:9090
    isDefault: true
    version: 1
    editable: false
